version: '3'

services:
  postgres:
    image: 'postgres:15-alpine'
    container_name: 'task5-postgres'
    ports:
      - 54321:5432
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=pass'
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: 'task5-app'
    ports:
      - 8081:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:54321/postgres
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
